// <auto-generated />
namespace Alpha_Immobilier_Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class firstcommit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(firstcommit));
        
        string IMigrationMetadata.Id
        {
            get { return "202104111411311_first commit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
